version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://root:@localhost:3306/micropost
          MAILER_FROM: micro@micropost.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: micropost
    steps:
      - checkout
      - run:
          name: Install PHP MySQL
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Wait for MySQL
          command: dockersize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migration
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction