<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ax_v3bs' shared service.

return $this->privates['.service_locator.Ax_v3bs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('microPost' => function (): \App\Entity\MicroPost {
    return ($this->privates['.errored..service_locator.Ax_v3bs.App\Entity\MicroPost'] ?? $this->load('getMicroPostService.php'));
}));
