<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ECBGt3n' shared service.

return $this->privates['.service_locator.ECBGt3n'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('notification' => function (): \App\Entity\Notification {
    return ($this->privates['.errored..service_locator.ECBGt3n.App\Entity\Notification'] ?? $this->load('getNotificationService.php'));
}));
