<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wHRqjfc' shared service.

return $this->privates['.service_locator.wHRqjfc'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('userWithPosts' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.wHRqjfc.App\Entity\User'] ?? $this->load('getUser3Service.php'));
}));
