<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mjfMAA.' shared service.

return $this->privates['.service_locator.mjfMAA.'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('post' => function (): \App\Entity\MicroPost {
    return ($this->privates['.errored..service_locator.mjfMAA..App\Entity\MicroPost'] ?? $this->load('getMicroPost2Service.php'));
}));
