<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Ax_v3bs.App\Entity\MicroPost' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.Ax_v3bs": it references class "App\\Entity\\MicroPost" but no such service exists.');
