<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMW9xu1l\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMW9xu1l/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMW9xu1l.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMW9xu1l\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMW9xu1l\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'MW9xu1l',
    'container.build_id' => '4f3a110f',
    'container.build_time' => 1542258658,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMW9xu1l');
